### PR TITLE
Fix vocative

### PR DESCRIPTION
**Pull request by Kikobeats**
A quick reference: http://www.grammar-monster.com/lessons/comma_with_dear_hello_and_hi.htm

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @Kikobeats,
Nice to meet you and thanks for the PR!

I would say that both forms of writing are acceptable and it comes down to a matter of preference. If you would prefer to have the comma right after the greeting (e.g. "Hi, Elad" instead of "Hi Elad,"), you can override `body.title` as follows:

```js
var email = {
    body: {
        // Title will override `name` and `greeting`
        title: 'Hi, Elad'
    }
};
```

I do believe that the latter ("Hi Elad,") is more appropriate for e-mails, especially in their plaintext version:

```
Hi Elad,
{intro and body}

Sincerely,
Kiko
```

Therefore, I do not think we should be modifying the greeting grammar at this stage, especially since it is a change in textual format that not all users of this package will be comfortable with.

But since `mailgen` allows overriding the title anyway, you can definitely use this type of greeting in your own e-mails.

Thanks again for your PR and suggestion! 👍

**Comment by Kikobeats** [comment]
Thanks for the tip 😄

**Comment by Kikobeats** [comment]
Thanks for the tip!

I'm using mailgen as part of [tom-microservice](https://github.com/Kikobeats/tom-microservice). it reduces a lot the part of setup fancy emails.

Thanks for create this project 😄

**Comment by eladnava** [comment]
Cool, my pleasure! 😄

**Pull request closed without merging**
