### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by italodeandra**
To remove `5 high severity vulnerabilities` warning.

### CODE REVIEW

**Comment by italodeandra** [comment]
Fixes #49 (already closed)

**Comment by italodeandra** [comment]
https://github.com/eladnava/mailgen/pull/50 and https://github.com/eladnava/mailgen/pull/51

are available to be installed frrom GitHub package repository: https://github.com/italodeandra/mailgen/packages/889262

**Comment by eladnava** [comment]
Thanks @italodeandra, fixed via commit 2d2feb5.

**Comment by eladnava** [comment]
Published as `2.0.15`.

**Pull request closed without merging**
