### PR TITLE
Remove copyright from all themes plaintext

### LINKED ISSUE #23: Remove copyright from plaintext e-mails
Currently, we output the copyright in plaintext e-mails. I think this is invalid, not to mention the fact that it currently contains HTML tags / entities:

```
Hi John Appleseed,

Welcome to Mailgen! We're very excited to have you on board.

To get started with Mailgen, please click here:
https://mailgen.js/confirm?s=d9729feb74992cc3482b350163a1a010

Need help, or have questions? Just reply to this email, we'd love to help.

Yours truly,
Mailgen

&copy; 2016 <a href="https://mailgen.js/" target="_blank">Mailgen</a>. All rights reserved.
```

In any case, it is broken. We should either remove it entirely or decode the HTML entities / remove tags. 

Any thoughts?

### PR DESCRIPTION
**Pull request by italodeandra**
Kind of fixes #23. In my opinion we don't need to show copyright on plaintext at all.

### CODE REVIEW

**Comment by italodeandra** [comment]
https://github.com/eladnava/mailgen/pull/50 and https://github.com/eladnava/mailgen/pull/51

are available to be installed frrom GitHub package repository: https://github.com/italodeandra/mailgen/packages/889262

**Comment by eladnava** [comment]
Thanks for the PR @italodeandra.

Rather than completely removing the copyright from plaintext e-mails (which many developers using this package might not expect, especially as it was present in previous versions), maybe we can add a toggle instead, such as a new property under `body` with a name similar to `noPlaintextCopyright`. When set to `true`, the copyright will be omitted from plaintext e-mails.

What do you think?

**Comment by eladnava** [comment]
In the meantime, commit https://github.com/eladnava/mailgen/commit/ef9d80b03fe2c366c65792aa41dc2edecdab7afc fixes the copyright formatting in plaintext e-mails (removes HTML tags + decodes HTML entities).

**Comment by italodeandra** [comment]
> What do you think?

Yes, if backwards compatibility on such thing (a copyright, not very important on the plaintext) is really required then I think it makes sense.

You can deny this PR and when I get the time I'll make the suggested change. If someone else is available, that's cool too.

**Comment by eladnava** [comment]
Awesome, thanks!

**Pull request closed without merging**
