### PR TITLE
Image "alt" attribute

### PR DESCRIPTION
**Pull request by nilsdnz**
I added the "alt" attribute to all img tags in the themes and gave it the value "Logo". This can improve the spam rating of mails a little bit.

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @nilsdnz,
Thanks so much for your contribution!

Seems like this could pose an adverse side effect -- Gmail and other mail clients take the "alt" text and display it in the e-mail preview:

Screen Shot 2020-05-06 at 2 40 28 PM

Unfortunately since this side effect isn't desirable, this PR cannot be merged at this time.

**Comment by nilsdnz** [comment]
Ok, no problem. Since even an empty alt attribute can improve spam score I simply removed the values. If you could reopen this I can update my PR.

**Comment by eladnava** [comment]
@nilsdnz Sounds good, reopened 👍

**Comment by nilsdnz** [comment]
Should be ready to merge!

**Comment by eladnava** [comment]
Awesome, thanks @nilsdnz, merged and published `2.0.11` 🎉

**Pull request merged**
